name: iBaalStatus
options:
  bundleIdPrefix: com.ibaal
  deploymentTarget:
    iOS: "16.0"
targets:
  iBaalStatus:
    type: application
    platform: iOS
    sources: [Sources]
    info:
      path: Sources/Info.plist
      properties:
        UILaunchScreen: {}
        NSPhotoLibraryUsageDescription: "iBaal Status butuh akses galeri untuk membaca video master 4K."
        NSPhotoLibraryAddUsageDescription: "iBaal Status butuh izin untuk menyimpan video 60 FPS ke galeri."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.ibaal.status
      TARGETED_DEVICE_FAMILY: "1"
      GENERATE_INFOPLIST_FILE: "YES"
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
